name: "Execute xcodebuild"
description: "Action to run xcodebuild with specified parameters"
inputs:
  action:
    description: "The action to perform with xcodebuild"
    required: true
    default: "build"
  workspace:
    description: "The workspace to use"
    required: true
    default: "Redzone.xcworkspace"
  scheme:
    description: "The scheme to use"
    required: true
    default: "Redzone"
  destination:
    description: "The device destination"
    required: true
    default: auto
  platform:
    description: "The platform of the destination - only necessary if destination is auto"
    required: false
    default: "iOS"
  working-directory:
    description: "The working directory"
    required: true

runs:
  using: composite
  steps:
   - name: "Set build destination"
     id: dest
     shell: zsh {0}
     working-directory: "${{ inputs.working-directory }}"
     run: |
      set -euo pipefail
      if [[ "${{ inputs.destination }}" = "auto" ]]; then
        DEVICES=$(xcodebuild -workspace "${{ inputs.workspace }}" -scheme "${{ inputs.scheme }}" -showdestinations | grep "${{ inputs.platform }} Simulator, arch:arm64")
        echo Available device specifiers:
        echo $DEVICES
        DEVICE=$(echo $DEVICES | head -n 1)
        [[ $DEVICE =~ .*id:([0-9A-Z\-]*).* ]]
        echo "destination=id=${match[1]}" >> $GITHUB_OUTPUT
        echo Selected device ID: ${match[1]}
      else
        echo "destination=${{ inputs.destination }}" >> $GITHUB_OUTPUT
      fi
   - name: "Run xcodebuild (${{ inputs.action }})"
     shell: zsh {0}
     working-directory: "${{ inputs.working-directory }}"
     run: |
      set -euo pipefail
      xcodebuild ${{ inputs.action }} \
        -workspace "${{ inputs.workspace }}" \
        -scheme "${{ inputs.scheme }}" \
        -destination "${{ steps.dest.outputs.destination }}" \
        -destination-timeout 5 \
        -derivedDataPath "${{ runner.temp }}/DerivedData" \
        -skipPackagePluginValidation \
        -skipMacroValidation \
        -disableAutomaticPackageResolution \
        -clonedSourcePackagesDirPath "${{ runner.temp }}/clonedSourcePackages" \
        2>&1 | xcbeautify --renderer github-actions

