disable_update_check: true
project: Redzone.xcodeproj
retain_codable_properties: true
retain_swift_ui_previews: true
schemes:
  - Redzone
strict: true
targets:
  - Redzone
  - RedzoneWidgets
  - RedzoneTests
  - RedzoneIntents
verbose: true
