name: Redzone - Web

on:
  push:
    branches: [ "main" ]
    paths: [ "redzone-web/functions/**", ".github/workflows/deploy-functions.yml" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: './redzone-web/functions/package-lock.json'
      - name: Install dependencies
        run: npm ci
        working-directory: ./redzone-web/functions
      - name: Compile sources
        run: npm run build
        working-directory: ./redzone-web/functions
      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only functions --message \"${{ github.event.head_commit.message }}\"
        working-directory: ./redzone-web/functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
