name: Redzone - NextJS

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Firebase App Hosting already watches pushed to main for its builds.
  # No need to do our own main branch build & deploy.
  pull_request:
    branches: [ "main" ]
    paths: 
      - redzone-web/src/**
      - redzone-web/apphosting.yaml
      - redzone-web/.firebaserc
      - redzone-web/next.config.ts
      - redzone-web/firebase.json
      - redzone-web/package-lock.json
      - redzone-web/package.json
      - redzone-web/package.json
      - redzone-web/tsconfig.json
      - .github/workflows/redzone-web.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: './redzone-web/package-lock.json'
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ./redzone-web/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./redzone-web/**/package-lock.json', './redzone-web/**/yarn.lock') }}-${{ hashFiles('./redzone-web/**.[jt]s', './redzone-web/**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('./redzone-web/**/package-lock.json', './redzone-web/**/yarn.lock') }}-
      - name: Install dependencies
        run: npm ci
        working-directory: ./redzone-web
      - name: Opt-out of Next.js telemetry
        run: npx --no-install next telemetry disable
        working-directory: ./redzone-web
      - name: Compile sources
        env:
          NEXT_PUBLIC_MAPKIT_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPKIT_TOKEN }}
          FB_ADMIN_CONFIG_ENCODED: ${{ secrets.FB_ADMIN_CONFIG_ENCODED }}
        run: npx --no-install next build
        working-directory: ./redzone-web
